### ISSUE TITLE
Consensus tree calculation pretends to run on mixed trees

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/phyltr#19]
I just tried to run `phyltr consensus` on a tree stream which accidentally had trees with a different taxon set mixed in there. `phyltr` failed with

```
Traceback (most recent call last):
  File "/vol/home/kaipingga/.local/bin/phyltr", line 11, in <module>
    load_entry_point('phyltr', 'console_scripts', 'phyltr')()
  File "/vol/home/kaipingga/devel/phyltr/phyltr/main.py", line 114, in run_command
    return class_.run_as_script()
  File "/vol/home/kaipingga/devel/phyltr/phyltr/commands/base.py", line 40, in run_as_script
    obj.init_sink(sys.stdout).consume(out_trees)
  File "/vol/home/kaipingga/devel/phyltr/phyltr/plumbing/sinks.py", line 12, in consume
    for t in stream:
  File "/vol/home/kaipingga/devel/phyltr/phyltr/commands/base.py", line 81, in consume
    for tree in self.postprocess():
  File "/vol/home/kaipingga/devel/phyltr/phyltr/commands/consensus.py", line 53, in postprocess
    t = self.build_consensus_tree()
  File "/vol/home/kaipingga/devel/phyltr/phyltr/commands/consensus.py", line 71, in build_consensus_tree
    assert prob == 1
AssertionError
```
which is confusing. Maybe it would be enough to just change that last line to `assert prob == 1, 'The taxonset {:} is present only in {:}% of input trees, do you have a mix of taxonsets in your input?'.format(all_leaves, prob*100)`

**Comment by lmaurits** [comment]
This looks like maybe another manifestation of #12 - @xrotwang and I bumped into a related problem with `phyltr clades` quite recently.

I'm wondering if commands which crucially depend upon a unique taxon set for their treestream should all subclass some abstract command which checks for violations of this and fails loudly ASAP.  This was all commands would respond to this problem consistently.

**Comment by xrotwang** [comment]
Alternatively, a flag (for all commands) could force such a check?

**Comment by lmaurits** [comment]
I agree it could be handy to optionally enforce such a check, even for commands where it is not logically necessary.

Maybe some kind of `phytlr assert` command would be handy.  By giving flags to that you could have it check various things (fixed taxon set, ultrametric trees, whatever), passing trees through without modification as long as the assertion is valid but noisily failing as soon as it is not.

**Comment by xrotwang** [comment]
Yep, this sounds good.

**Comment by Anaphory** [comment]
It's not #12, it's my own stupidity (I hadn't even considered there might be legit use cases), but your suggestions sounds great nonetheless.
